-- [marks]: https://vim.fandom.com/wiki/Using_marks
--
-- https://github.com/lusingander/serie

-- require 'config'
--

vim.g.mapleader = ' '
vim.g.maplocalleader = ' '

vim.filetype.add {
  extension = {
    env = 'dotenv',
    tpl = 'smarty',
  },
  filename = {
    ['.env'] = 'dotenv',
    ['index.tpl'] = 'smarty',
  },
  pattern = {
    ['%.env%.[%w_.-]+'] = 'dotenv',
    ['%.tpl$'] = 'smarty',
  },
}

vim.opt.guicursor = {
  'n-v-c:block', -- Normal, Visual, Command = bloque
  'i-ci-ve:ver25', -- Insert, Insert-completion, Visual-Select = barra vertical
  'r-cr:hor20', -- Replace = cursor subrayado
  'o:hor50', -- Operator-pending = subrayado más grueso
  'sm:block-blinkwait175-blinkoff150-blinkon175', -- visual feedback
}

--
-- require('lazy').setup({
--   'tpope/vim-sleuth',
--
--   {
--     -- Useful plugin to show you pending keybinds.
--     'folke/which-key.nvim',
--     event = 'VimEnter',
--     opts = {
--       icons = {
--         -- set icon mappings to true if you have a Nerd Font
--         mappings = true, -- vim.g.have_nerd_font,
--
--         -- If you are using a Nerd Font: set icons.keys to an empty table which will use the
--         -- default whick-key.nvim defined Nerd Font icons, otherwise define a string table
--         keys = {},
--       },
--
--       -- Document existing key chains
--       spec = {
--         { '<leader>c', group = '[C]ode', mode = { 'n', 'x' } },
--         { '<leader>d', group = '[D]ocument' },
--         { '<leader>r', group = '[R]ename' },
--         { '<leader>s', group = '[S]earch' },
--         { '<leader>w', group = '[W]orkspace' },
--         { '<leader>t', group = '[T]oggle' },
--         { '<leader>h', group = 'Git [H]unk', mode = { 'n', 'v' } },
--       },
--     },
--   },
--
--   -- LSP Plugins
--   {
--     -- `lazydev` configures Lua LSP for your Neovim config, runtime and plugins
--     -- used for completion, annotations and signatures of Neovim apis
--     'folke/lazydev.nvim',
--     ft = 'lua',
--     opts = {
--       library = {
--         -- Load luvit types when the `vim.uv` word is found
--         { path = 'luvit-meta/library', words = { 'vim%.uv' } },
--       },
--     },
--   },
--   { 'Bilal2453/luvit-meta', lazy = true },
--
--   {
--     'sainnhe/gruvbox-material',
--     priority = 1000,
--     lazy = false,
--     config = function()
--       vim.g.gruvbox_material_background = 'soft' -- hard, soft, medium
--       vim.g.gruvbox_material_foreground = 'mix' -- original, mix, material
--       vim.g.gruvbox_material_enable_italic = 1
--       vim.g.gruvbox_material_enable_bold = 1
--       vim.g.gruvbox_material_sign_column_background = 'none'
--       vim.g.gruvbox_material_diagnostic_virtual_text = 'colored' -- 'grey'`, `'colored'`, `'highlighted'
--
--       local grpid = vim.api.nvim_create_augroup('custom_highlights_gruvboxmaterial', {})
--       vim.api.nvim_create_autocmd('ColorScheme', {
--         group = grpid,
--         pattern = 'gruvbox-material',
--         command = 'hi NvimTreeNormal                     guibg=#181818 |'
--           .. 'hi NvimTreeEndOfBuffer                guibg=#181818 |'
--           .. 'hi NoiceCmdlinePopupBorderCmdline     guifg=#ea6962 guibg=#282828 |'
--           .. 'hi TelescopePromptBorder              guifg=#ea6962 guibg=#282828 |'
--           .. 'hi TelescopePromptNormal              guifg=#ea6962 guibg=#282828 |'
--           .. 'hi TelescopePromptTitle               guifg=#ea6962 guibg=#282828 |'
--           .. 'hi TelescopePromptPrefix              guifg=#ea6962 guibg=#282828 |'
--           .. 'hi TelescopePromptCounter             guifg=#ea6962 guibg=#282828 |'
--           .. 'hi TelescopePreviewTitle              guifg=#89b482 guibg=#282828 |'
--           .. 'hi TelescopePreviewBorder             guifg=#89b482 guibg=#282828 |'
--           .. 'hi TelescopeResultsTitle              guifg=#89b482 guibg=#282828 |'
--           .. 'hi TelescopeResultsBorder             guifg=#89b482 guibg=#282828 |'
--           .. 'hi TelescopeMatching                  guifg=#d8a657 guibg=#282828 |'
--           .. 'hi TelescopeSelection                 guifg=#ffffff guibg=#32302f |'
--           .. 'hi FloatBorder                        guibg=#282828 |' -- guifg=#ea6962
--           .. 'hi BqfPreviewBorder                   guifg=#ea6962 guibg=#282828 |'
--           .. 'hi NormalFloat                        guibg=#282828 |'
--           .. 'hi IndentBlanklineContextChar         guifg=#d3869b |'
--           .. 'hi StatusColumnBorder                 guifg=#232323 |'
--           .. 'hi StatusColumnBuffer                 guibg=#282828 |'
--           .. 'hi CursorLineNr                       guifg=#d8a657 |'
--           .. 'hi CodewindowBorder                   guifg=#ea6962 |'
--           .. 'hi TabLine                            guibg=#282828 |',
--       })
--     end,
--     init = function()
--       vim.cmd.colorscheme 'gruvbox-material'
--     end,
--   },
--
--   {
--     'ThePrimeagen/harpoon',
--     dependencies = { 'nvim-lua/plenary.nvim' },
--     branch = 'harpoon2',
--     config = function()
--       local harpoon = require 'harpoon'
--       harpoon:setup {
--         settings = {
--           save_on_toggle = true,
--           sync_on_ui_close = true,
--           -- key = function()
--           --   return vim.loop.cwd()
--           -- end,
--         },
--       }
--
--       harpoon:extend {
--         UI_CREATE = function(cx)
--           vim.keymap.set('n', 'J', function()
--             harpoon.ui:select_menu_item { vsplit = true }
--           end, { buffer = cx.bufnr })
--
--           vim.keymap.set('n', 'K', function()
--             harpoon.ui:select_menu_item { split = true }
--           end, { buffer = cx.bufnr })
--
--           -- Abrir en la ventana actual con Enter
--           vim.keymap.set('n', '<CR>', function()
--             harpoon.ui:select_menu_item()
--           end, { buffer = cx.bufnr })
--
--           -- Abrir en una nueva pestaña con Ctrl+t
--           vim.keymap.set('n', '<C-t>', function()
--             harpoon.ui:select_menu_item { tabedit = true }
--           end, { buffer = cx.bufnr })
--         end,
--       }
--     end,
--     opts = {
--       menu = {
--         -- width = vim.api.nvim_win_get_width(0) - 4,
--         width = math.floor(vim.api.nvim_win_get_width(0) * 0.5),
--       },
--       settings = {
--         save_on_toggle = true,
--       },
--     },
--     keys = function()
--       local keys = {
--         {
--           '<leader>+',
--           function()
--             require('harpoon'):list():add()
--           end,
--           desc = 'Harpoon File',
--         },
--         {
--           '<leader>=',
--           function()
--             local harpoon = require 'harpoon'
--             harpoon.ui:toggle_quick_menu(harpoon:list())
--           end,
--           desc = 'Harpoon Quick Menu',
--         },
--       }
--
--       for i = 1, 5 do
--         table.insert(keys, {
--           '<leader>' .. i,
--           function()
--             require('harpoon'):list():select(i)
--           end,
--           desc = 'Harpoon to File ' .. i,
--         })
--       end
--       return keys
--     end,
--   },
--
--   {
--     'nvim-lualine/lualine.nvim',
--     dependencies = { 'nvim-tree/nvim-web-devicons' },
--     event = 'VeryLazy',
--     opts = function()
--       local function is_vsplit()
--         -- Detecta si el layout superior es 'row' (ventanas lado a lado)
--         local function has_row(node)
--           if not node or type(node) ~= 'table' then
--             return false
--           end
--           if node[1] == 'row' then
--             return true
--           end
--           for i = 2, #node do
--             if has_row(node[i]) then
--               return true
--             end
--           end
--           return false
--         end
--         return has_row(vim.fn.winlayout())
--       end
--
--       local function win_is_narrow(w)
--         w = w or 0
--         return vim.api.nvim_win_get_width(w) < 60
--       end
--
--       local function file_icon()
--         local ok, dev = pcall(require, 'nvim-web-devicons')
--         if not ok then
--           return ''
--         end
--         local name, ext = vim.fn.expand '%:t', vim.fn.expand '%:e'
--         local icon = dev.get_icon(name, ext, { default = true })
--         return icon and (icon .. ' ') or ''
--       end
--
--       -- Nombre de archivo:
--       -- - En vsplit o ventana angosta => solo nombre
--       -- - Caso normal => ruta relativa (desde cwd)
--       local function smart_filename()
--         local name = ''
--         if is_vsplit() or win_is_narrow(0) then
--           name = vim.fn.expand '%:t'
--         else
--           -- relativo a cwd (si querés relativo a raíz git, se puede ajustar)
--           name = vim.fn.fnamemodify(vim.fn.expand '%:p', ':.')
--         end
--         if name == '' then
--           name = '[No Name]'
--         end
--
--         local modified = vim.bo.modified and ' [+]' or ''
--         return file_icon() .. name .. modified
--       end
--
--       -- Diagnósticos con íconos
--       local diagnostics = {
--         'diagnostics',
--         sources = { 'nvim_diagnostic' },
--         sections = { 'error', 'warn', 'info', 'hint' },
--         symbols = { error = ' ', warn = ' ', info = ' ', hint = '󱐋 ' },
--         colored = true,
--         update_in_insert = false,
--         always_visible = true,
--       }
--
--       -- Diff (usa gitsigns si está)
--       local diff = {
--         'diff',
--         symbols = { added = ' ', modified = ' ', removed = ' ' },
--         colored = true,
--         cond = function()
--           return not win_is_narrow(0)
--         end,
--       }
--
--       -- Línea/columna + total
--       local function cursor_and_total()
--         local l = vim.fn.line '.'
--         local c = vim.fn.col '.'
--         local total = vim.api.nvim_buf_line_count(0)
--         if win_is_narrow(0) then
--           return string.format('%d/%d', l, total)
--         end
--         return string.format('󰉸 %d│󱥖 %d  /%d', l, c, total)
--       end
--
--       -- reemplazá el componente de branch por este
--       local branch = {
--         'branch',
--         icon = '',
--         color = { gui = 'bold' },
--         -- oculta branch cuando hay vsplit
--         cond = function()
--           return not is_vsplit()
--         end,
--         -- (opcional) si NO hay vsplit, recorta nombres muy largos
--         -- fmt = function(head)
--         --   if not head then
--         --     return ''
--         --   end
--         --   return (#head > 24) and (head:sub(1, 21) .. '…') or head
--         -- end,
--       }
--
--       return {
--         options = {
--           theme = 'auto',
--           -- Por ventana para que en vsplit ambos lados muestren su info
--           globalstatus = false,
--           section_separators = '',
--           component_separators = '',
--           disabled_filetypes = { statusline = {} },
--           icons_enabled = true,
--         },
--         sections = {
--           -- sin modo
--           lualine_a = {},
--           -- Branch + Diff
--           lualine_b = {
--             -- { 'branch', icon = '', color = { gui = 'bold' } },
--             branch,
--             diff,
--           },
--           -- Nombre (path inteligente)
--           lualine_c = {
--             { smart_filename, padding = 1 },
--           },
--           -- Nada “ruidoso” en X
--           lualine_x = {
--             diagnostics, -- a la derecha pero visible en todas las ventanas
--           },
--           -- Posición + total líneas
--           lualine_y = {
--             { cursor_and_total, padding = 1 },
--           },
--           lualine_z = {},
--         },
--         inactive_sections = {
--           lualine_a = {},
--           lualine_b = {},
--           lualine_c = { { smart_filename } },
--           lualine_x = { diagnostics },
--           lualine_y = {},
--           lualine_z = {},
--         },
--         extensions = { 'quickfix', 'fugitive', 'man', 'nvim-tree', 'lazy' },
--       }
--     end,
--   },
--
--   { -- Collection of various small independent plugins/modules
--     'echasnovski/mini.nvim',
--     config = function()
--       -- Better Around/Inside textobjects
--       --
--       -- Examples:
--       --  - va)  - [V]isually select [A]round [)]paren
--       --  - yinq - [Y]ank [I]nside [N]ext [Q]uote
--       --  - ci'  - [C]hange [I]nside [']quote
--       require('mini.ai').setup { n_lines = 500 }
--
--       -- Add/delete/replace surroundings (brackets, quotes, etc.)
--       --
--       -- - saiw) - [S]urround [A]dd [I]nner [W]ord [)]Paren
--       -- - sd'   - [S]urround [D]elete [']quotes
--       -- - sr)'  - [S]urround [R]eplace [)] [']
--       require('mini.surround').setup()
--       -- require 'custom.plugins.mini.diff'
--     end,
--   },
--
--   -- The following two comments only work if you have downloaded the kickstart repo, not just copy pasted the
--   -- init.lua. If you want these files, they are in the repository, so you can just download them and
--   -- place them in the correct locations.
--
--   -- NOTE: Next step on your Neovim journey: Add/Configure additional plugins for Kickstart
--   --
--   --  Here are some example plugins that I've included in the Kickstart repository.
--   --  Uncomment any of the lines below to enable them (you will need to restart nvim).
--
--   -- require 'kickstart.plugins.debug',
--   -- require 'kickstart.plugins.indent_line',
--   -- require 'kickstart.plugins.autopairs',
--   -- require 'kickstart.plugins.neo-tree',
--   require 'kickstart.plugins.gitsigns', -- adds gitsigns recommend keymaps
--
--   -- NOTE: The import below can automatically add your own plugins, configuration, etc from `lua/custom/plugins/*.lua`
--   --    This is the easiest way to modularize your config.
--   --
--   --  Uncomment the following line and add your plugins to `lua/custom/plugins/*.lua` to get going.
--   --    For additional information, see `:help lazy.nvim-lazy.nvim-structuring-your-plugins`
--   { import = 'custom.plugins' },
-- }, {
--   change_detection = {
--     notify = false,
--   },
--   ui = {
--     icons = {},
--   },
-- })
--
--
-- -- The line beneath this is called `modeline`. See `:help modeline`
-- -- vim: ts=2 sts=2 sw=2 et

require 'config.autocmds'
require 'config.custom_functions'
require 'config.globals'
require 'config.keymaps'
require 'config.options'
require 'plugins'

vim.treesitter.language.register('bash', 'dotenv')
vim.treesitter.language.register('html', 'smarty')
