return {
  {
    "nvim-neo-tree/neo-tree.nvim",
    branch = "v3.x",
    cmd = "Neotree",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-tree/nvim-web-devicons",
      "MunifTanjim/nui.nvim",
    },
    keys = {
      {
        "<leader>e",
        "<cmd>Neotree filesystem toggle right<cr>",
        desc = "Explorer (filesystem)",
      },
      {
        "<leader>ge",
        "<cmd>Neotree git_status toggle float<cr>",
        desc = "Explorer (git status)",
      },
    },
    opts = {
      close_if_last_window = true,
      popup_border_style = "rounded",
      enable_git_status = true,
      enable_diagnostics = false,
      sources = { "filesystem", "git_status" },
      source_selector = {
        winbar = true,
        sources = {
          { source = "filesystem", display_name = " Files" },
          { source = "git_status", display_name = "󰊢 Git" },
        },
      },
      default_component_configs = {
        indent = {
          indent_size = 2,
          padding = 1,
          with_markers = true,
          indent_marker = "│",
          last_indent_marker = "└",
        },
        modified = { symbol = "" },
        git_status = {
          symbols = {
            added      = "",
            modified   = "",
            deleted    = "✖",
            renamed    = "󰁕",
            untracked  = "",
            ignored    = "",
            unstaged   = "󰄱",
            staged     = "",
            conflict   = "",
          },
        },
      },
      window = {
        position = "right",
        width = 35,
        mapping_options = { noremap = true, nowait = true },
        mappings = {
          ["<cr>"] = "open",
          ["l"]    = "open",
          ["h"]    = "close_node",
          ["J"]    = "open_vsplit",
          ["K"]    = "open_split",
          ["q"]    = "close_window",
          ["R"]    = "refresh",
          ["a"]    = { "add", config = { show_path = "relative" } },
          ["A"]    = "add_directory",
          ["d"]    = "delete",
          ["r"]    = "rename",
          ["y"]    = "copy_to_clipboard",
          ["x"]    = "cut_to_clipboard",
          ["p"]    = "paste_from_clipboard",
          ["c"]    = "copy",
          ["m"]    = "move",
          ["H"]    = "toggle_hidden",
          ["z"]    = "close_all_nodes",
          ["Z"]    = "expand_all_nodes",
          ["/"]    = "fuzzy_finder",
          ["?"]    = "show_help",
          -- Deshabilitar teclas usadas por flash.nvim globalmente
          ["s"]    = "none",
          ["S"]    = "none",
          ["f"]    = "none",
          ["F"]    = "none",
          ["t"]    = "none",
        },
      },
      filesystem = {
        filtered_items = {
          visible = false,
          hide_dotfiles = true,
          hide_gitignored = true,
        },
        follow_current_file = {
          enabled = true,
          leave_dirs_open = false,
        },
        group_empty_dirs = true,
        use_libuv_file_watcher = true,
      },
      git_status = {
        window = {
          position = "float",
          mappings = {
            ["<cr>"] = "open",
            ["J"]    = "open_vsplit",
            ["K"]    = "open_split",
            ["a"]    = "git_add_file",
            ["A"]    = "git_add_all",
            ["u"]    = "git_unstage_file",
            ["r"]    = "git_revert_file",
            ["q"]    = "close_window",
            ["?"]    = "show_help",
          },
        },
      },
    },
  },
}
